### ISSUE TITLE
Failed Installing

### ISSUE THREAD

**Issue by ltrottier** [szagoruyko/imagine-nn#39]
Hi,

I have problems install the repository. I cloned it, and here is the output of `luarocks make` :

```bash
luarocks make
cmake -E make_directory build;
cd build;
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/trottier/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/trottier/torch/install/lib/luarocks/rocks/inn/1.0-0"
   
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Torch7 in /home/trottier/torch/install
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr (found suitable version "7.5", minimum required is "6.5") 
-- Compiling for CUDA architecture: 3.5
-- Configuring done
-- Generating done
-- Build files have been written to: /home/trottier/Downloads/imagine-nn/build
cd build && make install
[ 33%] Building NVCC (Device) object CMakeFiles/inn.dir/inn_generated_SpatialStochasticPooling.cu.o
CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THStorage.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THStorageCopy.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCStorage.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCStorageCopy.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THTensor.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THTensorCopy.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THTensorRandom.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THTensorMath.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THTensorConv.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THTensorLapack.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensor.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorCopy.h


/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
CMake Error at inn_generated_SpatialStochasticPooling.cu.o.cmake:266 (message):
  Error generating file
  /home/trottier/Downloads/imagine-nn/build/CMakeFiles/inn.dir//./inn_generated_SpatialStochasticPooling.cu.o


CMakeFiles/inn.dir/build.make:70: recipe for target 'CMakeFiles/inn.dir/inn_generated_SpatialStochasticPooling.cu.o' failed
make[2]: *** [CMakeFiles/inn.dir/inn_generated_SpatialStochasticPooling.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/inn.dir/all' failed
make[1]: *** [CMakeFiles/inn.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Error: Build error: Failed installing.
```

**Comment by szagoruyko** [comment]
add this line to cmake
```cmake
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_FORCE_INLINES")
```
it's an issue with CUDA 7.5 that's fixed in CUDA 8

**Comment by ltrottier** [comment]
Thank you, it worked.

**Comment by DNGros** [comment]
I added the line @szagoruyko mentioned but am still getting a very similar error as the OP.
```
luarocks make
cmake -E make_directory build;
cd build;
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/dgros/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/dgros/torch/install/lib/luarocks/rocks/inn/1.0-0"
   
-- Found Torch7 in /home/dgros/torch/install
-- Automatic GPU detection failed. Building for all known architectures.
-- Compiling for CUDA architecture: 2.0 2.1(2.0) 3.0 3.5 5.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dgros/deepLearning/imagine-nn/build
cd build && make install
[ 33%] Building NVCC (Device) object CMakeFiles/inn.dir/inn_generated_SpatialStochasticPooling.cu.o
CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THStorage.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THStorageCopy.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCStorage.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCStorageCopy.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THTensor.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THTensorCopy.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THTensorRandom.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THTensorMath.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THTensorConv.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THTensorLapack.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensor.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorCopy.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorMath.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorMathBlas.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorMathPairwise.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorMathPointwise.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorMathReduce.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorMathCompare.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorMathCompareT.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorMasked.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorScatterGather.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorIndex.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorSort.h


/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
CMake Error at inn_generated_SpatialStochasticPooling.cu.o.cmake:266 (message):
  Error generating file
  /home/dgros/deepLearning/imagine-nn/build/CMakeFiles/inn.dir//./inn_generated_SpatialStochasticPooling.cu.o


CMakeFiles/inn.dir/build.make:248: recipe for target 'CMakeFiles/inn.dir/inn_generated_SpatialStochasticPooling.cu.o' failed
make[2]: *** [CMakeFiles/inn.dir/inn_generated_SpatialStochasticPooling.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/inn.dir/all' failed
make[1]: *** [CMakeFiles/inn.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Error: Build error: Failed installing.

```
I am not seeing as many initialization outputs, but the end error is the same.

This is with CUDA 7.5 and ubuntu 16.04
I have also tried running
```CC=gcc-4.9 CXX=g++-4.9 luarocks make```
and
```CC=gcc CXX=g++ luarocks make```
but both give the same error.

If it's useful, here are the packages I already have.
```
luarocks list
Warning: Failed loading manifest for /home/dgros/.luarocks/lib/luarocks/rocks: /home/dgros/.luarocks/lib/luarocks/rocks/manifest: No such file or directory

Installed rocks:
----------------

argcheck
   scm-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

class
   scm-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

coco
   scm-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

cudnn
   scm-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

cunn
   scm-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

cutorch
   scm-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

cwrap
   scm-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

dok
   scm-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

env
   scm-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

gnuplot
   scm-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

graph
   scm-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

image
   1.1.alpha-0 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

json
   1.0-0 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

lua-cjson
   2.1devel-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

luaffi
   scm-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

luafilesystem
   1.6.3-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

luasocket
   3.0rc1-2 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

md5
   1.2-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

nn
   scm-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

nngraph
   scm-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

nnx
   0.1-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

optim
   1.0.5-0 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

paths
   scm-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

penlight
   scm-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

qtlua
   scm-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

qttorch
   scm-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

sundown
   scm-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

sys
   1.1-0 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

tds
   scm-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

threads
   scm-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

torch
   scm-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

torchnet
   scm-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

trepl
   scm-1 (installed) - /home/dgros/torch/install/lib/luarocks/rocks

xlua
   1.0-0 (installed) - /home/dgros/torch/install/lib/luarocks/rocks
```

Any other ideas for sorting out this error?

**Comment by szagoruyko** [comment]
have you tried removing `build` folder and doing
```
CC=gcc-4.9 CXX=g++-4.9 luarocks make
```
again?

**Comment by DNGros** [comment]
@szagoruyko thanks for that advice. You're right, I should have been deleting the build folder every time. Unfortunately, I am still getting an error.

Here is the results:
```
CC=gcc-4.9 CXX=g++-4.9 luarocks make
cmake -E make_directory build;
cd build;
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/dgros/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/dgros/torch/install/lib/luarocks/rocks/inn/1.0-0"
   
-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/gcc-4.9
-- Check for working C compiler: /usr/bin/gcc-4.9 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-4.9
-- Check for working CXX compiler: /usr/bin/g++-4.9 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Torch7 in /home/dgros/torch/install
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-7.5 (found suitable version "7.5", minimum required is "6.5") 
-- Compiling for CUDA architecture: 5.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dgros/deepLearning/imagine-nn/build
cd build && make install
[ 33%] Building NVCC (Device) object CMakeFiles/inn.dir/inn_generated_SpatialStochasticPooling.cu.o
CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THStorage.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THStorageCopy.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCStorage.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCStorageCopy.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THTensor.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THTensorCopy.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THTensorRandom.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THTensorMath.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THTensorConv.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THTensorLapack.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensor.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorCopy.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorMath.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorMathBlas.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorMathPairwise.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorMathPointwise.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorMathReduce.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorMathCompare.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorMathCompareT.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorMasked.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorScatterGather.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorIndex.h


CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorSort.h


/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
CMake Error at inn_generated_SpatialStochasticPooling.cu.o.cmake:266 (message):
  Error generating file
  /home/dgros/deepLearning/imagine-nn/build/CMakeFiles/inn.dir//./inn_generated_SpatialStochasticPooling.cu.o


CMakeFiles/inn.dir/build.make:70: recipe for target 'CMakeFiles/inn.dir/inn_generated_SpatialStochasticPooling.cu.o' failed
make[2]: *** [CMakeFiles/inn.dir/inn_generated_SpatialStochasticPooling.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/inn.dir/all' failed
make[1]: *** [CMakeFiles/inn.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Error: Build error: Failed installing.
```
Just to try it and so that I am more closely matching the OP's configuration, I also installed gcc-4.8 and ran
`CC=gcc-4.8 CXX=g++-4.8 luarocks make`
That matches with 
```
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/gcc-4.8
...
-- Check for working CXX compiler: /usr/bin/g++-4.8
-- Check for working CXX compiler: /usr/bin/g++-4.8 -- works
```
but ultimately returns the same errors in the end.

The only significant difference I am seeing between what the OP had is that it's compileing for CUDA architecture 5.0 instead of 3.5. I'm running a GTX 745. Has anyone possibly seen any comparability problems with this architecture? Otherwise, is there anything else I could maybe be doing wrong?

**Comment by szagoruyko** [comment]
weird, it should work. Can you install CUDA 8?

**Comment by DNGros** [comment]
@szagoruyko 
Awesome, CUDA 8 fixed it. Thanks!
